language: node_js

cache:
  yarn: true

os: linux
dist: bionic

jobs:
  fast_finish: true
  include:
    - node_js: node
      env: LATEST=true
    - node_js: lts/*


notifications:
  email: false

before_deploy:
- yarn build

